import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Box, Center, Container, Flex, Grid, GridItem, IconButton, Spacer } from '@chakra-ui/react'
import Link from 'next/link'
import {
  Drawer,
  DrawerBody,
  DrawerFooter,
  DrawerHeader,
  DrawerOverlay,
  DrawerContent,
  DrawerCloseButton,
} from '@chakra-ui/react'
import { HamburgerIcon } from '@chakra-ui/icons'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Center>
          <Box border='1px solid gray.800'
            bg='gray.300' 
            w={['100%','75%','50%']} p={4}
            >
              <Flex>
                <Center>
                  Patient Data Uploader
                </Center>
                <Spacer/>
                <Box>
                  <IconButton aria-label='menu' icon={<HamburgerIcon/>}/>
                </Box>
              </Flex>
          </Box>

        </Center>
      </main>
    </>
  )
}
